# Please see the documentation for all configuration options:
# https://docs.github.com/github/administering-a-repository/configuration-options-for-dependency-updates
version: 2
updates:
# GitHub Actions
- package-ecosystem: "github-actions"
  directory: "/"
  schedule:
      interval: "weekly"
# Go
- package-ecosystem: "gomod"
  directory: "/"
  schedule:
    interval: "weekly"
  ignore:
  - dependency-name: "sigs.k8s.io/controller-runtime"
  # Ignore k8s and its transitives modules as they are upgraded manually
  # together with controller-runtime.
  - dependency-name: "k8s.io/*"
  - dependency-name: "go.etcd.io/*"
# Go modules in release-v2.8 branch
- package-ecosystem: "gomod"
  directory: "/"
  schedule:
    interval: "weekly"
  ignore:
    # Ignore controller-runtime as it's upgraded manually.
    - dependency-name: "sigs.k8s.io/controller-runtime"
    # Ignore k8s and its transitives modules as they are upgraded manually
    # together with controller-runtime.
    - dependency-name: "k8s.io/*"
    # Ignore wrangler
    - dependency-name: "github.com/rancher/wrangler"
    - dependency-name: "github.com/rancher/wrangler/v3"
    - dependency-name: "github.com/rancher/rancher/pkg/apis"
    - dependency-name: "go.etcd.io/*"
    - dependency-name: "github.com/Azure/azure-sdk-for-go"
    - dependency-name: "github.com/rancher/lasso"
  commit-message:
    prefix: ":seedling:"
  target-branch: "release-v2.8"

