#!/bin/bash
#
# Submit new AKS operator version against rancher/charts

set -ue

PREV_AKS_OPERATOR_VERSION="$1"   # e.g. 1.1.0-rc3
NEW_AKS_OPERATOR_VERSION="$2"
PREV_CHART_VERSION="$3"   # e.g. 101.2.0
NEW_CHART_VERSION="$4"
REPLACE="$5"              # remove previous version if `true`, otherwise add new

if [ -z "${GITHUB_WORKSPACE:-}" ]; then
    CHARTS_DIR="$(dirname -- "$0")/../../../charts"
else
    CHARTS_DIR="${GITHUB_WORKSPACE}/charts"
fi

pushd "${CHARTS_DIR}" > /dev/null

if [ ! -e ~/.gitconfig ]; then
    git config --global user.name "highlander-ci-bot"
    git config --global user.email highlander-ci@proton.me
fi

if [ ! -f bin/charts-build-scripts ]; then
    make pull-scripts
fi

find ./packages/rancher-aks-operator/ -type f -exec sed -i -e "s/${PREV_AKS_OPERATOR_VERSION}/${NEW_AKS_OPERATOR_VERSION}/g" {} \;
find ./packages/rancher-aks-operator/ -type f -exec sed -i -e "s/version: ${PREV_CHART_VERSION}/version: ${NEW_CHART_VERSION}/g" {} \;

if [ "${REPLACE}" == "true" ]; then
    sed -i -e "s/${PREV_CHART_VERSION}+up${PREV_AKS_OPERATOR_VERSION}/${NEW_CHART_VERSION}+up${NEW_AKS_OPERATOR_VERSION}/g" release.yaml
else
    sed -i -e "s/${PREV_CHART_VERSION}+up${PREV_AKS_OPERATOR_VERSION}/${PREV_CHART_VERSION}+up${PREV_AKS_OPERATOR_VERSION}\n${NEW_CHART_VERSION}+up${NEW_AKS_OPERATOR_VERSION}/g" release.yaml
    if grep -qv "rancher-aks-operator:" release.yaml; then

        cat <<< "rancher-aks-operator:
- ${PREV_CHART_VERSION}+up${PREV_AKS_OPERATOR_VERSION}
- ${NEW_CHART_VERSION}+up${NEW_AKS_OPERATOR_VERSION}
rancher-aks-operator-crd:
- ${PREV_CHART_VERSION}+up${PREV_AKS_OPERATOR_VERSION}
- ${NEW_CHART_VERSION}+up${NEW_AKS_OPERATOR_VERSION}" >> release.yaml

    fi
fi

git add packages/rancher-aks-operator release.yaml
git commit -m "Updating to AKS Operator v${NEW_AKS_OPERATOR_VERSION}"

if [ "${REPLACE}" == "true" ]; then
for i in rancher-aks-operator rancher-aks-operator-crd; do CHART=$i VERSION=${PREV_CHART_VERSION}+up${PREV_AKS_OPERATOR_VERSION} make remove; done
fi

PACKAGE=rancher-aks-operator make charts
git add assets/rancher-aks-operator* charts/rancher-aks-operator* index.yaml
git commit -m "Autogenerated changes for AKS Operator v${NEW_AKS_OPERATOR_VERSION}"

popd > /dev/null
