// Code generated by MockGen. DO NOT EDIT.
// Source: ../agentpools.go
//
// Generated by this command:
//
//	mockgen -destination agentpools_mock.go -package mock_services -source ../agentpools.go AgentPoolsClientInterface
//

// Package mock_services is a generated GoMock package.
package mock_services

import (
	context "context"
	reflect "reflect"

	runtime "github.com/Azure/azure-sdk-for-go/sdk/azcore/runtime"
	armcontainerservice "github.com/Azure/azure-sdk-for-go/sdk/resourcemanager/containerservice/armcontainerservice/v5"
	gomock "go.uber.org/mock/gomock"
)

// MockAgentPoolsClientInterface is a mock of AgentPoolsClientInterface interface.
type MockAgentPoolsClientInterface struct {
	ctrl     *gomock.Controller
	recorder *MockAgentPoolsClientInterfaceMockRecorder
}

// MockAgentPoolsClientInterfaceMockRecorder is the mock recorder for MockAgentPoolsClientInterface.
type MockAgentPoolsClientInterfaceMockRecorder struct {
	mock *MockAgentPoolsClientInterface
}

// NewMockAgentPoolsClientInterface creates a new mock instance.
func NewMockAgentPoolsClientInterface(ctrl *gomock.Controller) *MockAgentPoolsClientInterface {
	mock := &MockAgentPoolsClientInterface{ctrl: ctrl}
	mock.recorder = &MockAgentPoolsClientInterfaceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockAgentPoolsClientInterface) EXPECT() *MockAgentPoolsClientInterfaceMockRecorder {
	return m.recorder
}

// BeginCreateOrUpdate mocks base method.
func (m *MockAgentPoolsClientInterface) BeginCreateOrUpdate(ctx context.Context, resourceGroupName, clusterName, agentPoolName string, parameters armcontainerservice.AgentPool) (*runtime.Poller[armcontainerservice.AgentPoolsClientCreateOrUpdateResponse], error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "BeginCreateOrUpdate", ctx, resourceGroupName, clusterName, agentPoolName, parameters)
	ret0, _ := ret[0].(*runtime.Poller[armcontainerservice.AgentPoolsClientCreateOrUpdateResponse])
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// BeginCreateOrUpdate indicates an expected call of BeginCreateOrUpdate.
func (mr *MockAgentPoolsClientInterfaceMockRecorder) BeginCreateOrUpdate(ctx, resourceGroupName, clusterName, agentPoolName, parameters any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "BeginCreateOrUpdate", reflect.TypeOf((*MockAgentPoolsClientInterface)(nil).BeginCreateOrUpdate), ctx, resourceGroupName, clusterName, agentPoolName, parameters)
}

// BeginDelete mocks base method.
func (m *MockAgentPoolsClientInterface) BeginDelete(ctx context.Context, resourceGroupName, clusterName, agentPoolName string) (*runtime.Poller[armcontainerservice.AgentPoolsClientDeleteResponse], error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "BeginDelete", ctx, resourceGroupName, clusterName, agentPoolName)
	ret0, _ := ret[0].(*runtime.Poller[armcontainerservice.AgentPoolsClientDeleteResponse])
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// BeginDelete indicates an expected call of BeginDelete.
func (mr *MockAgentPoolsClientInterfaceMockRecorder) BeginDelete(ctx, resourceGroupName, clusterName, agentPoolName any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "BeginDelete", reflect.TypeOf((*MockAgentPoolsClientInterface)(nil).BeginDelete), ctx, resourceGroupName, clusterName, agentPoolName)
}
