// Code generated by MockGen. DO NOT EDIT.
// Source: ../subscriptions.go
//
// Generated by this command:
//
//	mockgen -destination subscriptions_mock.go -package mock_services -source ../subscriptions.go SubscriptionsClientInterface
//

// Package mock_services is a generated GoMock package.
package mock_services

import (
	reflect "reflect"

	runtime "github.com/Azure/azure-sdk-for-go/sdk/azcore/runtime"
	armsubscriptions "github.com/Azure/azure-sdk-for-go/sdk/resourcemanager/resources/armsubscriptions"
	gomock "go.uber.org/mock/gomock"
)

// MockSubscriptionsClientInterface is a mock of SubscriptionsClientInterface interface.
type MockSubscriptionsClientInterface struct {
	ctrl     *gomock.Controller
	recorder *MockSubscriptionsClientInterfaceMockRecorder
}

// MockSubscriptionsClientInterfaceMockRecorder is the mock recorder for MockSubscriptionsClientInterface.
type MockSubscriptionsClientInterfaceMockRecorder struct {
	mock *MockSubscriptionsClientInterface
}

// NewMockSubscriptionsClientInterface creates a new mock instance.
func NewMockSubscriptionsClientInterface(ctrl *gomock.Controller) *MockSubscriptionsClientInterface {
	mock := &MockSubscriptionsClientInterface{ctrl: ctrl}
	mock.recorder = &MockSubscriptionsClientInterfaceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockSubscriptionsClientInterface) EXPECT() *MockSubscriptionsClientInterfaceMockRecorder {
	return m.recorder
}

// NewListLocationsPager mocks base method.
func (m *MockSubscriptionsClientInterface) NewListLocationsPager(subscriptionID string, options *armsubscriptions.ClientListLocationsOptions) *runtime.Pager[armsubscriptions.ClientListLocationsResponse] {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "NewListLocationsPager", subscriptionID, options)
	ret0, _ := ret[0].(*runtime.Pager[armsubscriptions.ClientListLocationsResponse])
	return ret0
}

// NewListLocationsPager indicates an expected call of NewListLocationsPager.
func (mr *MockSubscriptionsClientInterfaceMockRecorder) NewListLocationsPager(subscriptionID, options any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "NewListLocationsPager", reflect.TypeOf((*MockSubscriptionsClientInterface)(nil).NewListLocationsPager), subscriptionID, options)
}
