name: Update AKS operator in rancher/rancher
on:
  workflow_dispatch:
    inputs:
      ref:
        description: "Branch to use for GitHub action workflow"
        required: true
        default: "master"
      rancher_ref:
        description: "Submit PR against the following rancher/rancher branch (e.g. release/v2.7)"
        required: true
        default: "release/v2.7"
      new_aks:
        description: "New AKS operator version (e.g. 1.2.0-rc.1), don't include the 'v'"
        required: true
        default: ""

env:
  GOARCH: amd64
  CGO_ENABLED: 0
  SETUP_GO_VERSION: '1.21.*'

jobs:
  create-rancher-pr:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          ref: ${{github.event.inputs.ref}}
          path: aks-operator
          persist-credentials: false
      - name: Checkout rancher/rancher
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          repository: rancher/rancher
          ref: ${{github.event.inputs.rancher_ref}}
          path: rancher
          persist-credentials: false
      - uses: actions/setup-go@v5
        with:
          go-version: ${{ env.SETUP_GO_VERSION }}
      - name: Run release script # release script is responsible for git add/commit
        run: ./aks-operator/.github/scripts/update-rancher-dep.sh ${{github.event.inputs.new_aks}}
      - name: Set timestamp
        run: echo "TIMESTAMP=$(date +'%s')" >> "$GITHUB_ENV"
      - name: Push changes
        env:
          USERNAME: highlander-ci-bot
          TOKEN: ${{ secrets.CI_BOT_TOKEN }}
        run: |
          git remote add bot-fork https://${USERNAME}:${TOKEN}@github.com/highlander-ci-bot/rancher.git
          git push bot-fork HEAD:${{github.event.inputs.new_aks}}-${{env.TIMESTAMP}}
      - name: Create PR
        uses: actions/github-script@60a0d83039c74a4aee543508d2ffcb1c3799cdea # v7.0.1
        with:
          github-token: ${{secrets.CI_BOT_TOKEN}}
          script: |
            github.pulls.create({
              owner: 'rancher',
              repo: 'rancher',
              head: 'highlander-ci-bot:${{github.event.inputs.new_aks}}-${{env.TIMESTAMP}}',
              base: ${{github.event.inputs.rancher_ref}},
              title: 'Update AKS operator to v${{github.event.inputs.new_aks}}',
              body: 'Update AKS operator to v${{github.event.inputs.new_aks}}\n\nChangelog: https://github.com/rancher/aks-operator/releases/tag/v${{github.event.inputs.new_aks}}\n\ncc @rancher/highlander'
            })
